export const truckData =[
    {   id: 1,
        truckId : 1234,
        driverID: 4521,
        status: "booked",
        max_km: 20,
        city_located: "Bangalore",
        destination: "Chennai",
        max_load: 100
    },
    {   id: 2,
        truckId : 1121,
        driverID: 4522,
        status: "booked",
        max_km: 20,
        city_located: "Chennai",
        destination: "Trichy",
        max_load: 100
    },
    {   id: 3,
        truckId : 1122,
        driverID: 4523,
        status: "booked",
        max_km: 20,
        city_located: "Ernakulam",
        destination: "Allepey",
        max_load: 100
    },
    {   id: 4,
        truckId : 1123,
        driverID: 4524,
        status: "booked",
        max_km: 20,
        city_located: "Mangalore",
        destination: "Mysore",
        max_load: 100
    },
    {   id: 5,
        truckId : 1124,
        driverID: 4525,
        status: "booked",
        max_km: 20,
        city_located: "Hyderabad",
        destination: "Amaravathi",
        max_load: 100
    },
    {   id: 6,
        truckId : 1125,
        driverID: 4526,
        status: "Unbooked",
        max_km: 20,
        city_located: "Mumbai",
        destination: "",
        max_load: 100
    },

]